import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Lock } from "lucide-react";
import { getCart } from "../(guest)/cart/page";
import { CartProduct } from "./checkout/page";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Checkout",
  description: "Generated by create next app",
};

export default async function CheckoutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cart = await getCart()
  const products = cart.data.products
  const totalItems = products.reduce((acc: number, product: CartProduct) => acc + product.quantity, 0)
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-amazon-background text-amazon-text flex flex-col min-h-screen`}
      >
        <header className="bg-amazon p-4 border-b border-gray-300">
          <div className="checkout-container flex justify-between items-center text-white">
            <Link href="/" className="flex items-center">
              <span className="text-2xl font-bold tracking-tighter">
                gadgets<span className="italic text-amazon-secondary">BD</span>
              </span>
            </Link>
            <h1 className="text-2xl font-normal hidden md:block">
              Checkout (<span className="text-amazon-secondary">{totalItems} items</span>)
            </h1>
            <Lock data-lucide="lock" className="w-5 h-5 text-gray-400" />
          </div>
        </header>

        {children}
        <footer className="bg-amazon-background py-10 border-t border-gray-300">
          <div className="checkout-container text-center text-[10px] text-gray-500 space-y-2">
            <div className="flex justify-center gap-6 text-amazon-blue text-xs mb-2">
              <a href="#" className="hover:underline">
                Conditions of Use
              </a>
              <a href="#" className="hover:underline">
                Privacy Notice
              </a>
              <a href="#" className="hover:underline">
                Help
              </a>
            </div>
            <p>
              © 2025 Gadgets BD - Premium Tech Marketplace. All rights reserved by LWS.
            </p>
          </div>
        </footer>

      </body>
    </html>
  );
}
